// =============================================================================
// Centralized Permission Registry & Role-Permission Matrix — Module 8A
// =============================================================================

import { COMPANY_PERMISSIONS } from './company';
import { EMPLOYEE_PERMISSIONS } from './employee';
import { VEHICLE_PERMISSIONS } from './vehicle';
import { DRIVER_PERMISSIONS } from './driver';
import { BOOKING_PERMISSIONS } from './booking';
import { TRIP_PERMISSIONS } from './trip';
import { PERMISSIONS as AUTH_PERMISSIONS } from './auth';

/**
 * Centralized UI Permissions Registry
 * Aggregates all permission tokens from Modules 2 through 7 without duplication.
 */
export const UI_PERMISSIONS = {
  // Module 2 — Auth / Platform
  USER_READ: AUTH_PERMISSIONS.USER_READ,
  USER_WRITE: AUTH_PERMISSIONS.USER_WRITE,
  USER_DELETE: AUTH_PERMISSIONS.USER_DELETE,
  PROFILE_READ: AUTH_PERMISSIONS.PROFILE_READ,
  PROFILE_WRITE: AUTH_PERMISSIONS.PROFILE_WRITE,
  ROLE_READ: AUTH_PERMISSIONS.ROLE_READ,
  ROLE_WRITE: AUTH_PERMISSIONS.ROLE_WRITE,
  ROLE_CREATE: AUTH_PERMISSIONS.ROLE_CREATE,
  ROLE_UPDATE: AUTH_PERMISSIONS.ROLE_UPDATE,
  ROLE_DELETE: AUTH_PERMISSIONS.ROLE_DELETE,
  PERMISSION_READ: AUTH_PERMISSIONS.PERMISSION_READ,
  PERMISSION_WRITE: AUTH_PERMISSIONS.PERMISSION_WRITE,
  PERMISSION_ASSIGN: AUTH_PERMISSIONS.PERMISSION_ASSIGN,

  // Module 3 — Company & Multi-Tenancy
  COMPANY_READ: COMPANY_PERMISSIONS.COMPANY_READ,
  COMPANY_CREATE: COMPANY_PERMISSIONS.COMPANY_CREATE,
  COMPANY_UPDATE: COMPANY_PERMISSIONS.COMPANY_UPDATE,
  COMPANY_DELETE: COMPANY_PERMISSIONS.COMPANY_DELETE,
  COMPANY_SETTINGS_READ: COMPANY_PERMISSIONS.COMPANY_SETTINGS_READ,
  COMPANY_SETTINGS_WRITE: COMPANY_PERMISSIONS.COMPANY_SETTINGS_WRITE,
  COMPANY_MEMBERS_READ: COMPANY_PERMISSIONS.COMPANY_MEMBERS_READ,
  COMPANY_MEMBERS_WRITE: COMPANY_PERMISSIONS.COMPANY_MEMBERS_WRITE,
  COMPANY_INVITE: COMPANY_PERMISSIONS.COMPANY_INVITE,

  // Module 4 — Employee Management
  EMPLOYEE_READ: EMPLOYEE_PERMISSIONS.EMPLOYEE_READ,
  EMPLOYEE_CREATE: EMPLOYEE_PERMISSIONS.EMPLOYEE_CREATE,
  EMPLOYEE_UPDATE: EMPLOYEE_PERMISSIONS.EMPLOYEE_UPDATE,
  EMPLOYEE_DELETE: EMPLOYEE_PERMISSIONS.EMPLOYEE_DELETE,
  EMPLOYEE_STATUS_WRITE: EMPLOYEE_PERMISSIONS.EMPLOYEE_STATUS_WRITE,
  EMPLOYEE_USER_LINK: EMPLOYEE_PERMISSIONS.EMPLOYEE_USER_LINK,

  // Module 5 — Vehicle Management
  VEHICLE_READ: VEHICLE_PERMISSIONS.VEHICLE_READ,
  VEHICLE_CREATE: VEHICLE_PERMISSIONS.VEHICLE_CREATE,
  VEHICLE_UPDATE: VEHICLE_PERMISSIONS.VEHICLE_UPDATE,
  VEHICLE_DELETE: VEHICLE_PERMISSIONS.VEHICLE_DELETE,
  VEHICLE_STATUS_WRITE: VEHICLE_PERMISSIONS.VEHICLE_STATUS_WRITE,
  VEHICLE_DOCUMENT_MANAGE: VEHICLE_PERMISSIONS.VEHICLE_DOC_MANAGE,
  VEHICLE_MAINTENANCE_MANAGE: VEHICLE_PERMISSIONS.VEHICLE_MAINT_MANAGE,

  // Module 6 — Driver Management
  DRIVER_READ: DRIVER_PERMISSIONS.DRIVER_READ,
  DRIVER_CREATE: DRIVER_PERMISSIONS.DRIVER_CREATE,
  DRIVER_UPDATE: DRIVER_PERMISSIONS.DRIVER_UPDATE,
  DRIVER_DELETE: DRIVER_PERMISSIONS.DRIVER_DELETE,
  DRIVER_STATUS_UPDATE: DRIVER_PERMISSIONS.DRIVER_STATUS_UPDATE,
  DRIVER_DUTY_UPDATE: DRIVER_PERMISSIONS.DRIVER_DUTY_UPDATE,
  DRIVER_DOCUMENTS_READ: DRIVER_PERMISSIONS.DRIVER_DOCUMENTS_READ,
  DRIVER_DOCUMENTS_WRITE: DRIVER_PERMISSIONS.DRIVER_DOCUMENTS_WRITE,
  DRIVER_VEHICLE_ASSIGN: DRIVER_PERMISSIONS.DRIVER_VEHICLE_ASSIGN,

  // Module 7 — Booking Management
  BOOKING_READ: BOOKING_PERMISSIONS.BOOKING_READ,
  BOOKING_CREATE: BOOKING_PERMISSIONS.BOOKING_CREATE,
  BOOKING_UPDATE: BOOKING_PERMISSIONS.BOOKING_UPDATE,
  BOOKING_DELETE: BOOKING_PERMISSIONS.BOOKING_DELETE,
  BOOKING_CONFIRM: BOOKING_PERMISSIONS.BOOKING_CONFIRM,
  BOOKING_CANCEL: BOOKING_PERMISSIONS.BOOKING_CANCEL,

  // Module 7 — Trip & Dispatch Management
  TRIP_READ: TRIP_PERMISSIONS.TRIP_READ,
  TRIP_CREATE: TRIP_PERMISSIONS.TRIP_CREATE,
  TRIP_UPDATE: TRIP_PERMISSIONS.TRIP_UPDATE,
  TRIP_DELETE: TRIP_PERMISSIONS.TRIP_DELETE,
  TRIP_ASSIGN_DRIVER: TRIP_PERMISSIONS.TRIP_ASSIGN_DRIVER,
  TRIP_ASSIGN_VEHICLE: TRIP_PERMISSIONS.TRIP_ASSIGN_VEHICLE,
  TRIP_DISPATCH: TRIP_PERMISSIONS.TRIP_DISPATCH,
  TRIP_UPDATE_STATUS: TRIP_PERMISSIONS.TRIP_UPDATE_STATUS,
  TRIP_CANCEL: TRIP_PERMISSIONS.TRIP_CANCEL,
} as const;

export type UiPermission = (typeof UI_PERMISSIONS)[keyof typeof UI_PERMISSIONS];

/**
 * Centralized Role → Permission Matrix
 * Maps every platform role and company membership role to its authorized permissions.
 *
 * Special behavior:
 * - SUPER_ADMIN has ['*'], granting access to all features across the platform.
 * - OWNER has full tenant authority.
 * - ADMIN has full operational and configuration authority.
 * - MANAGER has operational control (create/update), but cannot delete records or manage company billing/settings.
 * - DISPATCHER has trip, booking, and fleet operational dispatch visibility.
 * - ACCOUNTANT has financial/audit visibility for bookings, trips, and company profile.
 * - DRIVER has driver portal access: trips, vehicle info, duty toggle, profile.
 * - CUSTOMER has customer portal access: own bookings, trip status, profile.
 */
export const ROLE_PERMISSIONS: Record<string, readonly string[]> = {
  SUPER_ADMIN: ['*'],

  OWNER: [
    // Company
    UI_PERMISSIONS.COMPANY_READ,
    UI_PERMISSIONS.COMPANY_CREATE,
    UI_PERMISSIONS.COMPANY_UPDATE,
    UI_PERMISSIONS.COMPANY_DELETE,
    UI_PERMISSIONS.COMPANY_SETTINGS_READ,
    UI_PERMISSIONS.COMPANY_SETTINGS_WRITE,
    UI_PERMISSIONS.COMPANY_MEMBERS_READ,
    UI_PERMISSIONS.COMPANY_MEMBERS_WRITE,
    UI_PERMISSIONS.COMPANY_INVITE,

    // Employees
    UI_PERMISSIONS.EMPLOYEE_READ,
    UI_PERMISSIONS.EMPLOYEE_CREATE,
    UI_PERMISSIONS.EMPLOYEE_UPDATE,
    UI_PERMISSIONS.EMPLOYEE_DELETE,
    UI_PERMISSIONS.EMPLOYEE_STATUS_WRITE,
    UI_PERMISSIONS.EMPLOYEE_USER_LINK,

    // Vehicles
    UI_PERMISSIONS.VEHICLE_READ,
    UI_PERMISSIONS.VEHICLE_CREATE,
    UI_PERMISSIONS.VEHICLE_UPDATE,
    UI_PERMISSIONS.VEHICLE_DELETE,
    UI_PERMISSIONS.VEHICLE_STATUS_WRITE,
    UI_PERMISSIONS.VEHICLE_DOCUMENT_MANAGE,
    UI_PERMISSIONS.VEHICLE_MAINTENANCE_MANAGE,

    // Drivers
    UI_PERMISSIONS.DRIVER_READ,
    UI_PERMISSIONS.DRIVER_CREATE,
    UI_PERMISSIONS.DRIVER_UPDATE,
    UI_PERMISSIONS.DRIVER_DELETE,
    UI_PERMISSIONS.DRIVER_STATUS_UPDATE,
    UI_PERMISSIONS.DRIVER_DUTY_UPDATE,
    UI_PERMISSIONS.DRIVER_DOCUMENTS_READ,
    UI_PERMISSIONS.DRIVER_DOCUMENTS_WRITE,
    UI_PERMISSIONS.DRIVER_VEHICLE_ASSIGN,

    // Bookings
    UI_PERMISSIONS.BOOKING_READ,
    UI_PERMISSIONS.BOOKING_CREATE,
    UI_PERMISSIONS.BOOKING_UPDATE,
    UI_PERMISSIONS.BOOKING_DELETE,
    UI_PERMISSIONS.BOOKING_CONFIRM,
    UI_PERMISSIONS.BOOKING_CANCEL,

    // Trips
    UI_PERMISSIONS.TRIP_READ,
    UI_PERMISSIONS.TRIP_CREATE,
    UI_PERMISSIONS.TRIP_UPDATE,
    UI_PERMISSIONS.TRIP_DELETE,
    UI_PERMISSIONS.TRIP_ASSIGN_DRIVER,
    UI_PERMISSIONS.TRIP_ASSIGN_VEHICLE,
    UI_PERMISSIONS.TRIP_DISPATCH,
    UI_PERMISSIONS.TRIP_UPDATE_STATUS,
    UI_PERMISSIONS.TRIP_CANCEL,

    // User / Auth / RBAC
    UI_PERMISSIONS.USER_READ,
    UI_PERMISSIONS.USER_WRITE,
    UI_PERMISSIONS.PROFILE_READ,
    UI_PERMISSIONS.PROFILE_WRITE,
    UI_PERMISSIONS.ROLE_READ,
    UI_PERMISSIONS.ROLE_WRITE,
    UI_PERMISSIONS.ROLE_CREATE,
    UI_PERMISSIONS.ROLE_UPDATE,
    UI_PERMISSIONS.ROLE_DELETE,
    UI_PERMISSIONS.PERMISSION_READ,
    UI_PERMISSIONS.PERMISSION_WRITE,
    UI_PERMISSIONS.PERMISSION_ASSIGN,
  ],

  ADMIN: [
    // Company
    UI_PERMISSIONS.COMPANY_READ,
    UI_PERMISSIONS.COMPANY_UPDATE,
    UI_PERMISSIONS.COMPANY_SETTINGS_READ,
    UI_PERMISSIONS.COMPANY_SETTINGS_WRITE,
    UI_PERMISSIONS.COMPANY_MEMBERS_READ,
    UI_PERMISSIONS.COMPANY_MEMBERS_WRITE,
    UI_PERMISSIONS.COMPANY_INVITE,

    // Employees
    UI_PERMISSIONS.EMPLOYEE_READ,
    UI_PERMISSIONS.EMPLOYEE_CREATE,
    UI_PERMISSIONS.EMPLOYEE_UPDATE,
    UI_PERMISSIONS.EMPLOYEE_DELETE,
    UI_PERMISSIONS.EMPLOYEE_STATUS_WRITE,
    UI_PERMISSIONS.EMPLOYEE_USER_LINK,

    // Vehicles
    UI_PERMISSIONS.VEHICLE_READ,
    UI_PERMISSIONS.VEHICLE_CREATE,
    UI_PERMISSIONS.VEHICLE_UPDATE,
    UI_PERMISSIONS.VEHICLE_DELETE,
    UI_PERMISSIONS.VEHICLE_STATUS_WRITE,
    UI_PERMISSIONS.VEHICLE_DOCUMENT_MANAGE,
    UI_PERMISSIONS.VEHICLE_MAINTENANCE_MANAGE,

    // Drivers
    UI_PERMISSIONS.DRIVER_READ,
    UI_PERMISSIONS.DRIVER_CREATE,
    UI_PERMISSIONS.DRIVER_UPDATE,
    UI_PERMISSIONS.DRIVER_DELETE,
    UI_PERMISSIONS.DRIVER_STATUS_UPDATE,
    UI_PERMISSIONS.DRIVER_DUTY_UPDATE,
    UI_PERMISSIONS.DRIVER_DOCUMENTS_READ,
    UI_PERMISSIONS.DRIVER_DOCUMENTS_WRITE,
    UI_PERMISSIONS.DRIVER_VEHICLE_ASSIGN,

    // Bookings
    UI_PERMISSIONS.BOOKING_READ,
    UI_PERMISSIONS.BOOKING_CREATE,
    UI_PERMISSIONS.BOOKING_UPDATE,
    UI_PERMISSIONS.BOOKING_DELETE,
    UI_PERMISSIONS.BOOKING_CONFIRM,
    UI_PERMISSIONS.BOOKING_CANCEL,

    // Trips
    UI_PERMISSIONS.TRIP_READ,
    UI_PERMISSIONS.TRIP_CREATE,
    UI_PERMISSIONS.TRIP_UPDATE,
    UI_PERMISSIONS.TRIP_DELETE,
    UI_PERMISSIONS.TRIP_ASSIGN_DRIVER,
    UI_PERMISSIONS.TRIP_ASSIGN_VEHICLE,
    UI_PERMISSIONS.TRIP_DISPATCH,
    UI_PERMISSIONS.TRIP_UPDATE_STATUS,
    UI_PERMISSIONS.TRIP_CANCEL,

    // User / Auth / RBAC
    UI_PERMISSIONS.USER_READ,
    UI_PERMISSIONS.USER_WRITE,
    UI_PERMISSIONS.PROFILE_READ,
    UI_PERMISSIONS.PROFILE_WRITE,
    UI_PERMISSIONS.ROLE_READ,
    UI_PERMISSIONS.PERMISSION_READ,
  ],

  MANAGER: [
    // Company
    UI_PERMISSIONS.COMPANY_READ,
    UI_PERMISSIONS.COMPANY_MEMBERS_READ,

    // Employees (no delete)
    UI_PERMISSIONS.EMPLOYEE_READ,
    UI_PERMISSIONS.EMPLOYEE_CREATE,
    UI_PERMISSIONS.EMPLOYEE_UPDATE,
    UI_PERMISSIONS.EMPLOYEE_STATUS_WRITE,

    // Vehicles (no delete)
    UI_PERMISSIONS.VEHICLE_READ,
    UI_PERMISSIONS.VEHICLE_CREATE,
    UI_PERMISSIONS.VEHICLE_UPDATE,
    UI_PERMISSIONS.VEHICLE_STATUS_WRITE,
    UI_PERMISSIONS.VEHICLE_DOCUMENT_MANAGE,
    UI_PERMISSIONS.VEHICLE_MAINTENANCE_MANAGE,

    // Drivers (no delete)
    UI_PERMISSIONS.DRIVER_READ,
    UI_PERMISSIONS.DRIVER_CREATE,
    UI_PERMISSIONS.DRIVER_UPDATE,
    UI_PERMISSIONS.DRIVER_STATUS_UPDATE,
    UI_PERMISSIONS.DRIVER_DUTY_UPDATE,
    UI_PERMISSIONS.DRIVER_DOCUMENTS_READ,
    UI_PERMISSIONS.DRIVER_DOCUMENTS_WRITE,
    UI_PERMISSIONS.DRIVER_VEHICLE_ASSIGN,

    // Bookings (no delete)
    UI_PERMISSIONS.BOOKING_READ,
    UI_PERMISSIONS.BOOKING_CREATE,
    UI_PERMISSIONS.BOOKING_UPDATE,
    UI_PERMISSIONS.BOOKING_CONFIRM,
    UI_PERMISSIONS.BOOKING_CANCEL,

    // Trips (no delete)
    UI_PERMISSIONS.TRIP_READ,
    UI_PERMISSIONS.TRIP_CREATE,
    UI_PERMISSIONS.TRIP_UPDATE,
    UI_PERMISSIONS.TRIP_ASSIGN_DRIVER,
    UI_PERMISSIONS.TRIP_ASSIGN_VEHICLE,
    UI_PERMISSIONS.TRIP_DISPATCH,
    UI_PERMISSIONS.TRIP_UPDATE_STATUS,
    UI_PERMISSIONS.TRIP_CANCEL,

    // User / Profile
    UI_PERMISSIONS.USER_READ,
    UI_PERMISSIONS.PROFILE_READ,
    UI_PERMISSIONS.PROFILE_WRITE,
  ],

  DISPATCHER: [
    UI_PERMISSIONS.COMPANY_READ,

    // Fleet visibility
    UI_PERMISSIONS.VEHICLE_READ,
    UI_PERMISSIONS.DRIVER_READ,
    UI_PERMISSIONS.DRIVER_DUTY_UPDATE,
    UI_PERMISSIONS.DRIVER_VEHICLE_ASSIGN,

    // Booking management
    UI_PERMISSIONS.BOOKING_READ,
    UI_PERMISSIONS.BOOKING_CREATE,
    UI_PERMISSIONS.BOOKING_UPDATE,
    UI_PERMISSIONS.BOOKING_CONFIRM,
    UI_PERMISSIONS.BOOKING_CANCEL,

    // Operational Trips & Dispatch
    UI_PERMISSIONS.TRIP_READ,
    UI_PERMISSIONS.TRIP_CREATE,
    UI_PERMISSIONS.TRIP_UPDATE,
    UI_PERMISSIONS.TRIP_ASSIGN_DRIVER,
    UI_PERMISSIONS.TRIP_ASSIGN_VEHICLE,
    UI_PERMISSIONS.TRIP_DISPATCH,
    UI_PERMISSIONS.TRIP_UPDATE_STATUS,
    UI_PERMISSIONS.TRIP_CANCEL,

    UI_PERMISSIONS.PROFILE_READ,
    UI_PERMISSIONS.PROFILE_WRITE,
  ],

  ACCOUNTANT: [
    UI_PERMISSIONS.COMPANY_READ,
    UI_PERMISSIONS.BOOKING_READ,
    UI_PERMISSIONS.TRIP_READ,
    UI_PERMISSIONS.PROFILE_READ,
    UI_PERMISSIONS.PROFILE_WRITE,
  ],

  DRIVER: [
    UI_PERMISSIONS.TRIP_READ,
    UI_PERMISSIONS.TRIP_UPDATE_STATUS,
    UI_PERMISSIONS.DRIVER_DUTY_UPDATE,
    UI_PERMISSIONS.VEHICLE_READ,
    UI_PERMISSIONS.PROFILE_READ,
    UI_PERMISSIONS.PROFILE_WRITE,
  ],

  CUSTOMER: [
    UI_PERMISSIONS.BOOKING_READ,
    UI_PERMISSIONS.BOOKING_CREATE,
    UI_PERMISSIONS.BOOKING_CANCEL,
    UI_PERMISSIONS.TRIP_READ,
    UI_PERMISSIONS.PROFILE_READ,
    UI_PERMISSIONS.PROFILE_WRITE,
  ],

  MEMBER: [
    UI_PERMISSIONS.COMPANY_READ,
    UI_PERMISSIONS.PROFILE_READ,
    UI_PERMISSIONS.PROFILE_WRITE,
  ],
} as const;
